### ISSUE TITLE
Crear los HTML para las vistas del sistema de gestion de inventario del proyecto

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Proyecto-Final-Chaskibunes-Tercer-semestre#6]
Hay que crear una carpeta templates, con los archivos index.html y lista_productos.html para que el codigo funcione

**Comment by valentinalbornozz** [comment]
Creamos la carpeta template con index.html

**Comment by mairacar** [comment]
Carga de lista de productos html
