### ISSUE TITLE
Agregar archivo css para diseño del sistema de gestion de inventario hecho en HTML

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Proyecto-Final-Chaskibunes-Tercer-semestre#7]
Generar una carpeta static, dentro de la misma una css y luego un archivo .css, este fichero .css tendra el diseño de las paginas html

**Comment by G4llegus** [comment]
Se genero correctamente la carpeta ''static'' con la carpeta ''css'' con su correspondiente archivo de estilos para el html
